### ISSUE TITLE
Shapefile download gives error

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#104]
Both Pariya and I tried to download the shapefile data from the site today and received an error that redirected directly to github. It reads:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Both of us were using google chrome

**Comment by iangmhill** [comment]
I think this issue was fixed by @ericyoungberg in late April in these two commits:

- Add download notices to share buttons. Fix shapefile concurrency issue. 87a6b9efa4d883fe1267be4de14a3eb42bbc5a9e
- Fix shapefile export 6bd9e28c7516aa583e9d3ba8c39a968b5129873b

@ericyoungberg Has launch.ericyoungberg.com been updated since April 24?

**Comment by iangmhill** [comment]
We've resolved this on `develop` so I'm closing this issue.
