### ISSUE TITLE
Eliminate Presence Validations for Development Fields without Presence Requirement Indicator in the UI

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#127]
The new development UI does not have asterisks for some fields, including group quarters (gq_pop), but these fields are required and throw a presence validation error if the user fails to fill them out.

Check the test suite to see if the views are relying on the presence of this data.

**Comment by mzagaja** [comment]
Potential solution path: "Make the default values 0. This should only be the case for developments that are In Construction or Completed. When commercial uses or residential types are entered at all, we check to make sure the sum matches the total. Adding 0s by default would trigger this validation too early in Projected and Planned projects."

**Comment by allthesignals** [comment]
PR #118 removes the Ember edit page and replaces it with a server-side edit page. But it doesn't replace the development creation page. So we have two places for handling #new and #edit actions on Development, instead of one (which was the original case). 

It sounds like the real issue was adding the "log_message parameter to the development form", which was confusing with Ember because it was dealing with a separate "Edit" model. Not sure what other issues there were. So while PR #118 made it easier to add log messages, but it removed the ability to link organizations as development team members.

Ultimately, we used Ember for add/edit actions because of the need for "live view helpers and dynamic values" to handle the requested features for these views. For example, the street view edit feature needed to bind with changes made to the map point placement view. The binding was also actually "one-way" instead of the conventional two-way binding. All this logic required complexity in the client side.

I bring this up because it's not clear if we should switch everything to server-rendered pages or not. Because the validations for Developments are complex, with certain field validations being conditional, it might be desirable to use Ember to handle that UI. The only issue we'd have to solve is having the API accept the `log message` field. Alternatively, we could switch everything back to server-rendered pages, but would need to rebuild a number of things, including map point placement (which no longer exists in the edit page) and ability to add development team memberships.

**Comment by mzagaja** [comment]
Well it sounds like this is a pretty large omelette to unscramble so here is my current thinking:

1. Keep the views separate for now. It lacks elegance but allows us to punt on the issue of rebuilding one interface or the other until the next sprint.

2. New development pages should be fairly uniform in their validation requirements so I think we either rip out the relevant validations from the models if we don't want them (and rails should update the edit view for free) or alternatively if we want the validation then we just need to update the ember page.

I understand why you bring this up. It looks and smells like technical debt! Every time we have to change something in the edit page we may have to change something in the new development page. Unfortunately it looks to me like the interest rate here is low and the principal is high. Unless you think resurrecting the Ember page for the edit developments thing is easy (or likely to knock out a large swath of our outstanding issues), I think we just make our monthly payment now and consider dedicating time to paying the rest of this off in the next version.

**Comment by allthesignals** [comment]
I mean, not all debt is necessarily bad debt. I think the decision made in your second point will determine how I move forward... going back to the original issue, required field asterisks were not being included where fields were required. But those change depending on the development status (completed=more requirements, project=fewer requirements). 

If conditional validations are removed for now (things like gqpop, etc, which is arguably okay given the edit proposal system already in place), but uniform validations (things like name, year, etc) remain, I won't build that UI logic out until later. Do you plan to remove those validations for now? Then a later issue can be made to improve the UX design of the form.
