### ISSUE TITLE
Fix Sub-Type Square Footage Calculation

### ISSUE THREAD

**Issue by mzagaja** [MAPC/massbuilds#142]
Currently commercial use type square footage (floor area by use type) numbers are 0.01 * the actual value that we would expect. We need to fix this so the math reflects the actual square footage.

**Comment by allthesignals** [comment]
I attempted to reproduce this bug on master and it did not reproduce with a new development. After talking to Tim we learned that the issue is specific to certain developments that were imported. The suggested path forward for this is to develop a rake task that finds all the developments where the sub-types of square footage do not add up to the total commercial square footage and then multiply the matching development's sub-type square footages by 100 to fix the values.

**Comment by mzagaja** [comment]
It turns out the fa_hotel column has mostly NULL values. This means that in the majority of cases when the Postgres database does the addition function it does not return an integer to compare to the commsf column. It appears that this does not let the database return the expected list of rows that the rake task asks for. A solution to this problem may be to run a SQL query against the database to set all the fa_hotel column values to 0.

Since we are dealing with a live database I would like to make sure we have a mechanism for a quick rollback if making these changes to the database breaks something, and also a sane backup and restore strategy. It is not a good idea to edit a live server without these safeguards in place since data can be permanently lost or the service can break. We are going to talk with Susan to ask what mechanisms are in place before trying this solution.

**Comment by arouault** [comment]
Though the sub-type seems to be fixed, the total percentage row still reads 100% even when all sub-type commercial square footage is 0% 

![screen shot 2017-01-13 at 1 45 58 pm](https://cloud.githubusercontent.com/assets/1305629/21941414/aa621d46-d996-11e6-911d-b9e5787986cc.png)

**Comment by mzagaja** [comment]
That was filed as issue #154 because this issue is a database issue and the percentage issue seems to be an issue in the Rails app itself.
