### ISSUE TITLE
Make massbuilds.com/developments compatible with IE

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#218]
Right now www.massbuilds.com/developments does not work with IE. Since we are marketing this to municipal staff, it's important that the site work with basic tools. 

Issue #217 was made to be the short-term fix to this (message directing to another browser) but in the long term we want users to be able to use MassBuilds on all web platforms.

**Comment by allthesignals** [comment]
@sannphilbrick 

Thank you, Sarah! I think as a rule we won't support older versions of IE (8,9, and 10) as they are [not supported](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support) by Microsoft anymore, however, the expected behavior should be to show users a "Sorry, please upgrade your browser" screen, which is handled on the backend. @mzagaja, can you comment on which browser versions the Rails app currently throws that message for?

My initial question was going to be "which browser version and OS platform is the user using?" but I went ahead and generated screenshots of every combo of Windows OS and IE version 7-Edge:
[windowsIEscreens.zip](https://github.com/MAPC/massbuilds/files/1008479/windowsIEscreens.zip)

Here are results:
- Windows 7 
  - IE 8: Graceful Degradation, shows message
  - IE 9: Graceful Degradation, shows message
  - IE 10: **Blank screen, this is a BUG** 
  - IE 11: **Blank screen, this is a BUG** 
- Windows 8
  - IE 10: **Blank screen, this is a BUG** 
- Windows 8.1
  - IE 10: **Blank screen, this is a BUG** 
  - IE 11: **Blank screen, this is a BUG** 
- Windows 10
  - Edge 14.0: Functional Map
  - IE 11: **Blank screen, this is a BUG** 
- Windows XP
  - IE 6: Graceful Degradation, shows message
  - IE 7: Graceful Degradation, shows message

Over half of the permutations don't behave correctly. Because we support IE 11 (because it continues to be supported by Microsoft), three of these need to be investigated and fixed ASAP. The others occur on IE 10. We should handle that by trying to fix the compatibility issue on IE 11 first, then seeing if it fixes it for IE 10. If the compatibility issue runs much deeper, we should update the Rails app and have it throw the upgrade message. 

This assumes that we have no intention of spending extra resources to make things compatible with unsupported IE 10 software. If that's not the case, we should discuss further and see how many users that will affect. (Going to loop in @arouault on this final point).

**Comment by allthesignals** [comment]
As a side note, browser support looks 100% across a random sample of different OS/browser combos (excluding IE), with the exception of visual glitches for old OS's:

[randomSampleBrowsers.zip](https://github.com/MAPC/massbuilds/files/1008607/randomSampleBrowsers.zip)

**Comment by allthesignals** [comment]
Verifying that staging works for our supported IE/Windows versions: 
<img width="1077" alt="screen shot 2017-06-13 at 1 56 38 pm" src="https://user-images.githubusercontent.com/5004319/27096780-38b61fbe-5040-11e7-8ec6-5402dc3604b8.png">

@sannphilbrick see Slack channel for link to staging. Thanks.

**Comment by mzagaja** [comment]
I deployed to prod.
