### ISSUE TITLE
Export data to various file formats

### ISSUE THREAD

**Issue by arouault** [MAPC/massbuilds#27]
- [ ] geojson
- [x] shapefile
- [x] csv

**Comment by TimReardon** [comment]
geojson so nice we listed it twice!

**Comment by mzagaja** [comment]
I think I got shapefile working but I can't test it with puma so will have to set it up on production using the instructions at https://stackoverflow.com/questions/44370604/rails-file-download-via-send-file-is-slow-is-x-sendfile-or-similar-available-in.

**Comment by mzagaja** [comment]
Mysteriously this worked (due to a fix I had made earlier in the day yesterday) at the end of the day yesterday. The fix for some reason failed to push from my work machine so I need to push it up tomorrow from the office. But basically learned that if you leave a .zip file in the rails public folder and then your browser calls for that .zip file, the HTTP request will not hit the normal rails controller code path. So a fix I thought would work and tested failed. But I didn't realize I had a sneaky interloper. Will push this tomorrow morning.

**Comment by iangmhill** [comment]
@arouault Will we ever want to download geojson? Can this issue be closed?

**Comment by arouault** [comment]
I can't imagine a planner using this format. I think csv is sufficient. Thanks!
